Repository SKU-Homepage/frontend, pull requests merged in 2025-02, with the labels that each got.

#9 🔀 Merge: finish notice page NoticeBtn UI, NoticeBtnSection
  src/app/notice/page.tsx
  src/assets/images/notice/direction.svg
  src/assets/images/notice/empty-heart.svg
  src/components/notice/index.tsx
  src/components/notice/notice-btn/NoticeBtn.Section.tsx
  src/components/notice/notice-btn/NoticeBtn.tsx
  src/components/notice/timeInfro/TimeInformation.tsx
Labels: enhancement

#10 [Design] : 탭바 UI/UX 개선 및 MainWrapper 추가
  public/images/active-my.svg
  public/images/edit.svg
  public/images/ex.svg
  public/images/gray-calendar.svg
  public/images/gray-heart.svg
  public/images/gray-speaker.svg
  public/images/profile_background.png
  src/app/layout.tsx
  src/app/profile/page.tsx
  src/assets/images/.gitkeep
  src/components/home/index.tsx
  src/components/profile/ProfileImg.tsx
  src/components/profile/Service.tsx
  src/components/profile/UserInfo.tsx
  src/components/profile/index.tsx
  src/components/tabBar/Containers.tsx
  src/utils/MainWrapper.tsx
Labels: enhancement

#11 🎨 Design : 마이페이지 UI 완성 및 Tip 컴포넌트 높이 축소
  public/images/book.svg
  public/images/note.svg
  public/images/warning.svg
  src/app/profile/page.tsx
  src/components/common/Tip.tsx
  src/components/profile/InfoSection.tsx
  src/components/profile/Service.tsx
  src/components/profile/index.tsx
  src/components/tabBar/index.tsx
Labels: enhancement

#15 ✨ Feat : 위젯 추가 로직 구현
  src/components/home/AddWidget/AddWidget.tsx
  src/components/home/AddWidget/AddWidgetModal.tsx
  src/components/home/AddWidget/AddWidgetModalContent.tsx
  src/components/home/AddWidget/NewWidgets.tsx
  src/components/home/AddWidget/Widget.tsx
  src/components/home/MyWidgets.tsx
  src/components/home/WidgetSection.tsx
  src/components/home/index.tsx
  src/constants/widgets/index.ts
  src/stores/atoms.ts
Labels: enhancement

#26 🎨 Design : 마이페이지, 알림 목록, 메인 페이지, 로그인 페이지 UI 제작 완료
  .prettierrc
  package-lock.json
  package.json
  public/images/back.svg
  public/images/bell.svg
  public/images/bin.svg
  public/images/hamburger.svg
  public/images/home_background.png
  public/images/login_background.png
  public/images/login_logo.svg
  public/images/three-dot.svg
  public/images/x.svg
  src/app/notifications/page.tsx
  src/app/page.tsx
  src/app/profile/layout.tsx
  src/app/profile/page.tsx
  src/components/header/BackBtn.tsx
  src/components/header/Header.tsx
  src/components/header/HeaderBtn.tsx
  src/components/home/AddWidget/Widget.tsx
  src/components/home/MyWidgets.tsx
  src/components/home/header/Header.tsx
  src/components/home/index.tsx
  src/components/login/LoginBtn.tsx
  src/components/login/index.tsx
  src/components/notifications/DeleteBtn.tsx
  src/components/notifications/HeaderSection.tsx
  src/components/notifications/index.tsx
  src/components/profile/InfoSection/InfoSection.tsx
  src/components/profile/InfoSection/ProfileImg.tsx
  src/components/profile/InfoSection/UserInfo.tsx
  src/components/profile/index.tsx
  src/constants/widgets/index.ts
  src/stores/atoms.ts
  src/styles/globals.css
  src/utils/MainWrapper.tsx
Labels: documentation, enhancement

#32 🔧 Settings : axios 설정 및 firebase 초기 설정
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  public/service-worker.js
  src/api/axios.ts
  src/app/api/auth/refresh/route.ts
  src/app/layout.tsx
  src/styles/globals.css
  src/utils/Providers.tsx
  src/utils/firebase.ts
  src/utils/get-query-client.ts
Labels: documentation, enhancement

#35 [Feat] : 로그인 구현, 메인 페이지 및 마이 페이지 api 연동
  public/images/cloud.png
  src/api/axios.ts
  src/app/api/auth/callback/google/loginHook.ts
  src/app/api/auth/callback/google/page.tsx
  src/app/layout.tsx
  src/components/common/Loading.tsx
  src/components/header/Header.tsx
  src/components/home/TableSection.tsx
  src/components/home/TimeTable/Lecture.tsx
  src/components/home/TimeTable/Lectures.tsx
  src/components/home/TimeTable/TableBody.tsx
  src/components/home/TimeTable/TableHeader.tsx
  src/components/home/TimeTable/TimeTable.tsx
  src/components/home/index.tsx
  src/components/login/LoginBtn.tsx
  src/components/profile/InfoSection/InfoSection.tsx
  src/components/profile/InfoSection/UserInfo.tsx
  src/components/profile/InfoSection/UserInfoSection.tsx
  src/components/profile/index.tsx
  src/hooks/homeHooks/index.ts
  src/hooks/profileHooks/index.ts
Labels: documentation, enhancement

#36 [Feat] : 로그인 및 파이어베이스 환경변수 설정
  src/app/api/auth/callback/google/loginHook.ts
  src/utils/firebase.ts
Labels: documentation
